#!/usr/bin/env python3
"""
使用 pycookiecheat 库导出 Chrome 所有 cookies
输出到 stdout，可以使用重定向保存到文件

用法:
    python3 export_cookies_pycookiecheat.py > cookies.txt
"""

import sys
import os


def export_all_cookies():
    """导出所有 Chrome cookies 到 stdout"""

    try:
        import pycookiecheat
    except ImportError:
        print("❌ pycookiecheat 未安装", file=sys.stderr)
        print("\n请运行以下命令安装:", file=sys.stderr)
        print("  pip3 install pycookiecheat", file=sys.stderr)
        return False

    try:
        import sqlite3
        import shutil
        import tempfile
        from pathlib import Path
        from datetime import datetime, timedelta

        # 获取 Chrome cookies 数据库路径
        if sys.platform == "darwin":  # macOS
            cookies_db = Path.home() / "Library/Application Support/Google/Chrome/Default/Cookies"
        elif sys.platform == "win32":  # Windows
            cookies_db = Path(os.getenv("LOCALAPPDATA")) / "Google/Chrome/User Data/Default/Network/Cookies"
        elif sys.platform.startswith("linux"):  # Linux
            cookies_db = Path.home() / ".config/google-chrome/Default/Cookies"
        else:
            print(f"❌ 不支持的操作系统: {sys.platform}", file=sys.stderr)
            return False

        if not cookies_db.exists():
            print(f"❌ 找不到 Chrome cookies 文件: {cookies_db}", file=sys.stderr)
            return False

        # 复制数据库到临时文件
        temp_db = tempfile.NamedTemporaryFile(delete=False, suffix='.db')
        temp_db.close()

        try:
            shutil.copy2(cookies_db, temp_db.name)
            conn = sqlite3.connect(temp_db.name)
            cursor = conn.cursor()

            # 获取所有 cookies
            query = """
                SELECT host_key, name, value, path, expires_utc, is_secure, is_httponly, encrypted_value
                FROM cookies
                ORDER BY host_key, name
            """
            cursor.execute(query)
            all_cookies = cursor.fetchall()
            conn.close()

            if not all_cookies:
                print("❌ 没有找到任何 cookies", file=sys.stderr)
                return False

            print(f"🔍 找到 {len(all_cookies)} 个 cookies", file=sys.stderr)

            # 解密 cookies
            print(f"🔓 正在解密...", file=sys.stderr)

            # 输出 Netscape 格式的头部
            print("# Netscape HTTP Cookie File")
            print("# This file was generated by pycookiecheat")
            print("# Edit at your own risk.")
            print()

            # 使用 pycookiecheat 解密
            # 由于 pycookiecheat 是按域名导出的，我们需要收集所有域名
            domains = set()
            for cookie in all_cookies:
                host_key = cookie[0]
                # 提取域名（去掉前导的点）
                domain = host_key.lstrip('.')
                if domain:
                    domains.add(domain)

            # 对每个域名导出 cookies
            exported_count = 0
            processed_domains = set()

            for domain in sorted(domains):
                if domain in processed_domains:
                    continue

                try:
                    cookies = pycookiecheat.chrome_cookies(domain)
                    if cookies:
                        processed_domains.add(domain)
                        for name, value in cookies.items():
                            # 从原始数据中查找匹配的 cookie 以获取完整信息
                            cookie_data = None
                            for c in all_cookies:
                                if c[1] == name and domain in c[0]:
                                    cookie_data = c
                                    break

                            if cookie_data:
                                host_key, _, _, path, expires_utc, is_secure, is_httponly, _ = cookie_data

                                # 转换过期时间
                                if expires_utc:
                                    chrome_epoch = datetime(1601, 1, 1)
                                    unix_epoch = datetime(1970, 1, 1)
                                    delta = (unix_epoch - chrome_epoch).total_seconds()
                                    expires = int(expires_utc / 1000000 - delta)
                                else:
                                    expires = int((datetime.now() + timedelta(days=365*10)).timestamp())

                                flag = "TRUE" if host_key.startswith('.') else "FALSE"
                                path = path or "/"
                                secure = "TRUE" if is_secure else "FALSE"

                                print(f"{host_key}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
                                exported_count += 1
                except:
                    # 某些域名可能无法导出，跳过
                    pass

            print(f"✅ 成功导出 {exported_count} 个 cookies", file=sys.stderr)
            return True

        finally:
            # 清理临时文件
            try:
                os.unlink(temp_db.name)
            except:
                pass

    except Exception as e:
        print(f"❌ 导出失败: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc(file=sys.stderr)
        return False


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] in ['-h', '--help', 'help']:
        print("用法: python3 export_cookies_pycookiecheat.py > cookies.txt", file=sys.stderr)
        print("\n导出所有 Chrome cookies 到 stdout", file=sys.stderr)
        print("使用重定向 (>) 保存到文件", file=sys.stderr)
        print("\n示例:", file=sys.stderr)
        print("  python3 export_cookies_pycookiecheat.py > cookies.txt", file=sys.stderr)
        print("  python3 export_cookies_pycookiecheat.py > app/cookies.txt", file=sys.stderr)
        sys.exit(0)

    success = export_all_cookies()
    sys.exit(0 if success else 1)
