#!/usr/bin/env python3
"""
Firefox Cookies 导出工具 (无加密，100% 成功率)
Firefox 的 cookies 存储在 SQLite 数据库中，不加密，非常容易读取

用法:
    python3 export_cookies_firefox.py > cookies.txt
"""

import sys
import os
import sqlite3
import shutil
import tempfile
from pathlib import Path
from datetime import datetime


def find_firefox_profile():
    """查找 Firefox 配置文件目录"""

    if sys.platform == "darwin":  # macOS
        base_path = Path.home() / "Library/Application Support/Firefox/Profiles"
    elif sys.platform == "win32":  # Windows
        base_path = Path(os.getenv("APPDATA")) / "Mozilla/Firefox/Profiles"
    else:  # Linux
        base_path = Path.home() / ".mozilla/firefox"

    if not base_path.exists():
        return None

    # 查找默认配置文件（通常包含 .default 或 .default-release）
    profiles = []
    for profile_dir in base_path.iterdir():
        if profile_dir.is_dir():
            cookies_db = profile_dir / "cookies.sqlite"
            if cookies_db.exists():
                profiles.append(cookies_db)

    if not profiles:
        return None

    # 返回最新修改的配置文件
    return max(profiles, key=lambda p: p.stat().st_mtime)


def export_firefox_cookies():
    """导出 Firefox cookies"""

    # 查找 Firefox cookies 数据库
    cookies_db = find_firefox_profile()

    if not cookies_db:
        print("❌ 找不到 Firefox cookies 文件", file=sys.stderr)
        print("\n可能的原因:", file=sys.stderr)
        print("  1. Firefox 未安装", file=sys.stderr)
        print("  2. Firefox 从未使用过（没有访问过任何网站）", file=sys.stderr)
        print("\n预期路径:", file=sys.stderr)
        if sys.platform.startswith("linux"):
            print("  ~/.mozilla/firefox/*/cookies.sqlite", file=sys.stderr)
        elif sys.platform == "darwin":
            print("  ~/Library/Application Support/Firefox/Profiles/*/cookies.sqlite", file=sys.stderr)
        return False

    print(f"📂 使用 Firefox cookies 文件: {cookies_db}", file=sys.stderr)

    # 创建临时副本（避免数据库锁定问题）
    temp_db = tempfile.NamedTemporaryFile(delete=False, suffix='.sqlite')
    temp_db.close()

    try:
        shutil.copy2(cookies_db, temp_db.name)

        # 连接到数据库
        conn = sqlite3.connect(temp_db.name)
        cursor = conn.cursor()

        # 查询所有 cookies
        # Firefox cookies 表结构：
        # name, value, host, path, expiry, isSecure, isHttpOnly
        query = """
            SELECT host, name, value, path, expiry, isSecure
            FROM moz_cookies
            ORDER BY host, name
        """

        cursor.execute(query)
        cookies = cursor.fetchall()
        conn.close()

        if not cookies:
            print("❌ Firefox cookies 数据库为空", file=sys.stderr)
            print("   请先使用 Firefox 访问一些网站", file=sys.stderr)
            return False

        print(f"✅ 找到 {len(cookies)} 个 cookies", file=sys.stderr)

        # 输出 Netscape 格式
        print("# Netscape HTTP Cookie File")
        print("# This file was generated by export_cookies_firefox.py")
        print("# Firefox cookies are NOT encrypted - 100% success rate!")
        print("# Edit at your own risk.")
        print()

        exported_count = 0

        for cookie in cookies:
            host, name, value, path, expiry, is_secure = cookie

            # 跳过空值
            if not host or not name or value is None:
                continue

            # Netscape 格式
            # domain flag path secure expiry name value

            # 域名标志
            flag = "TRUE" if host.startswith('.') else "FALSE"

            # 路径
            path = path or "/"

            # 安全标志
            secure = "TRUE" if is_secure else "FALSE"

            # 过期时间（Firefox 使用 Unix 时间戳，单位是秒）
            if expiry:
                expires = int(expiry)
            else:
                # 会话 cookie，设置为 10 年后
                expires = int(datetime.now().timestamp()) + 365*24*3600*10

            print(f"{host}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
            exported_count += 1

        print(f"✅ 成功导出 {exported_count} 个 cookies", file=sys.stderr)
        return True

    except Exception as e:
        print(f"❌ 导出失败: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc(file=sys.stderr)
        return False
    finally:
        # 清理临时文件
        try:
            os.unlink(temp_db.name)
        except:
            pass


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] in ['-h', '--help', 'help']:
        print("=" * 60, file=sys.stderr)
        print("Firefox Cookies 导出工具", file=sys.stderr)
        print("=" * 60, file=sys.stderr)
        print("\n特点:", file=sys.stderr)
        print("  ✅ Firefox cookies 不加密", file=sys.stderr)
        print("  ✅ 100% 成功率", file=sys.stderr)
        print("  ✅ 无需额外依赖", file=sys.stderr)
        print("  ✅ 适用于所有 Firefox 版本", file=sys.stderr)
        print("\n用法:", file=sys.stderr)
        print("  python3 export_cookies_firefox.py > cookies.txt", file=sys.stderr)
        print("\n建议:", file=sys.stderr)
        print("  1. 先关闭 Firefox (可选，但推荐):", file=sys.stderr)
        print("     pkill firefox", file=sys.stderr)
        print("  2. 导出 cookies:", file=sys.stderr)
        print("     python3 export_cookies_firefox.py > cookies.txt", file=sys.stderr)
        print("  3. 验证结果:", file=sys.stderr)
        print("     grep -v '^#' cookies.txt | wc -l", file=sys.stderr)
        print("=" * 60, file=sys.stderr)
        sys.exit(0)

    success = export_firefox_cookies()
    sys.exit(0 if success else 1)
